dependencies:
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1"
networks:
  rinkeby:
    eth_usd: "0x8A753747A1Fa494EC906cE90E9f37563A8AF630e"
  mainnet-fork-dev:
    eth_usd: "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419"
dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}
